### ISSUE TITLE
Problems installing and running petiteFinder

### ISSUE THREAD

**Issue by Clarion** [javathejhut/petiteFinder#1]
Hi Chris,
thanks for putting together the petiteFinder.

I was trying to install it following your guide. However, in the end I got an error message. I am using a Mac and I followed the CPU installation guide. Here is the command that I run:
`python petiteFinder.py predict -d cpu -i ./demo/input_images/ -o ./demo/output/ -p frequency_only`
The error message is the following:
`Traceback (most recent call last):
  File "petiteFinder.py", line 370, in <module>
    coco_prediction_dict = perform_inference_coco(args.input_path, args.device, args.grande_size)
  File "petiteFinder.py", line 166, in perform_inference_coco
    detection_model.load_model()
  File "/Users/c_osman/mambaforge-pypy3/envs/petiteEnv/lib/python3.7/site-packages/sahi/model.py", line 185, in load_model
    device=self.device,
  File "/Users/c_osman/mambaforge-pypy3/envs/petiteEnv/lib/python3.7/site-packages/mmdet/apis/inference.py", line 46, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "/Users/c_osman/mambaforge-pypy3/envs/petiteEnv/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 638, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/Users/c_osman/mambaforge-pypy3/envs/petiteEnv/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 572, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/Users/c_osman/mambaforge-pypy3/envs/petiteEnv/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 314, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/Users/c_osman/mambaforge-pypy3/envs/petiteEnv/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 334, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/Users/c_osman/mambaforge-pypy3/envs/petiteEnv/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/c_osman/mambaforge-pypy3/envs/petiteEnv/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

Any help would be much appreciated!

**Comment by zhan4429** [comment]
Hi @Clarion , I got the same error. Have you figured out how to fix it? Thanks

**Comment by Clarion** [comment]
Hi,

no, I never heard back.

Best,

Christof
-------------------------------------------------------------
Christof Osman						
									
Würmstrasse 34						
82131 Stockdorf						
Germany								
									
Phone: 	+49 (0)176 23130090			
Mail:	***@***.***

**Comment by zhan4429** [comment]
Thanks, Christof, hopefully, the developers can update the installation instructions.

**Comment by javathejhut** [comment]
Hi @Clarion and @zhan4429. Apologies for not responding sooner, I wasn't notified at all until zhan recently commented. I will try to reproduce this issue and get back to you. I don't have a Mac but will see if I can reproduce the error on windows/linux.

**Comment by zhan4429** [comment]
Hi Chris,

I installed it on Linux (Redhat7). I only tried the CPU version. I suspected certain Python modules installed by pip caused the version incompatibility. 

Currently, containerization is widely used. It will be great if you can create and share a container via Docker/singularity. 

Thanks for helping us solve the issue. 

Best,
Yucheng

**Comment by javathejhut** [comment]
@Clarion @zhan4429, as a temporary fix, please try downloading the model weights [here](https://drive.google.com/file/d/1mzZwpaZqLtrc_yF06-rTRfGozmiJLkAz/view?usp=sharing&authuser=0) and replacing the file with the same name in petiteFinder/config/model_weights/. It appears from my testing that git-lfs was only downloading the pointer to the file, and not the entire weights file. This is a temporary fix.. I will work on a more permanent solution (probably involving my lfs quota). This fixed the same error your encountered on a fresh Ubuntu install for me. Hope this helps and please let me know if this worked for you.

**Comment by zhan4429** [comment]
Thanks @javathejhut, your solution fixed the issue. I only tested the cpu version. Actually, during my installation, I also noticed other issues. According to your installation instructions, I should run "mim install mmdet". However, I noticed that the installed versions of mmcv and mmdet did not work as expected. I did some tests, and in the end I used the below two lines to install it.

mim install mmdet==2.25.2
pip install mmcv-full==1.7.0

**Comment by javathejhut** [comment]
Hi @zhan4429 and @Clarion, thanks for raising this. I updated the repo and readme with new streamlined installation instructions. I hope this helps users in the future, cheers!

To use the new dependency management system: 

a) Run git pull to get the latest main branch.
b) Discard your old Conda/Python environment.
c) Follow the updated [Installation section in the README](https://github.com/javathejhut/petiteFinder#installation). (It is now a streamlined make install process).

Let me know if you run into any issues with the new setup and I'll be happy to help. Otherwise, feel free to close this issue!
